# Generated by Django 2.1.5 on 2019-02-22 11:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default='M', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(max_length=1)),
                ('telephone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_de_visite', models.DateTimeField(default=django.utils.timezone.now)),
                ('heure_darrive', models.DateTimeField(default=django.utils.timezone.now)),
                ('heure_depart', models.DateTimeField(blank=True, null=True)),
                ('motif', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='e_registre.Personne')),
            ],
            bases=('e_registre.personne',),
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='e_registre.Personne')),
                ('filiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='e_registre.Filiere')),
            ],
            bases=('e_registre.personne',),
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='e_registre.Personne')),
                ('departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='e_registre.Departement')),
            ],
            bases=('e_registre.personne',),
        ),
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='e_registre.Personne')),
            ],
            bases=('e_registre.personne',),
        ),
        migrations.AddField(
            model_name='visite',
            name='visiteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_registre.Personne'),
        ),
        migrations.AddField(
            model_name='enseignement',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_registre.Matiere'),
        ),
        migrations.AddField(
            model_name='enseignement',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_registre.Enseignant'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='matieres',
            field=models.ManyToManyField(related_name='_enseignant_matieres_+', through='e_registre.Enseignement', to='e_registre.Matiere'),
        ),
    ]
