# Generated by Django 2.1.5 on 2019-02-22 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('e_registre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visite',
            name='date_de_visite',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visite',
            name='heure_darrive',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visite',
            name='heure_depart',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visite',
            name='motif',
            field=models.TextField(blank=True, null=True),
        ),
    ]
